### ISSUE TITLE
[TNG] Timestamp Attribut Darstellungs Fehler

### ISSUE THREAD

**Issue by pixelianer** [MetaModels/attribute_timestamp#10]
Contao 3.3.3
MM TNG über Composer

Beim klick auf das Datums Icon fehlt die komplette Formatierung des JS Kalenders
( Siehe links oben und links unten )
Die Datepicker.js wird geladen, die Console gibt keinerlei Errors. Die Funktion des Cal. funktioniert auch weiterhin nur eben greifen hier anscheinend keine CSS Regeln.

![20140705-171828-899](https://cloud.githubusercontent.com/assets/2776503/3486905/aa3f6d1c-0457-11e4-8655-8399077b6d4a.jpg)

**Comment by cyberlussi** [comment]
Ja. Habe mal mit dem letzten Stand das ganze nochmal probiert: gleiches Problem ... nur anderes CSS. Wäre echt super, wenn das mal gefixt werden würde.

![2015-03-28_12_53_59_-_events_-_contao_open_source_cms_3_2](https://cloud.githubusercontent.com/assets/4976687/6880961/88c03f4a-d549-11e4-90ec-4d3f9c00c94b.png)

**Comment by cyberlussi** [comment]
Ja ... wiederhole mich ungern ... Wäre echt super, wenn das mal gefixt werden würde. Auch die neuesten Pakete zeigen das gleiche Verhalten.

metamodels/bundle_attributes 	1.0.1 		
metapackage 		metamodels/bundle_filter 	1.0.0 		
contao-module 		metamodels/core 	2.0.0-alpha1

Oder soll ich das doch mal in ein neues Ticket verlegen?

**Comment by cyberlussi** [comment]
Hm. Ich habe heute versucht den Fehler irgendwo zu lokalisieren, weil er mich nervt und dachte, diesen im datetime picker zu finden, habe aber doch nix gefunden. Dabei ist mir aber auch aufgefallen, dass Contao Core bei der Zeit gar keinen Picker anbietet (warum nur?!?). Ist jetzt nicht die beste Lösung, den Picker einfach wegzulassen, aber so wie es jetzt ist, ist es auch nicht gut.

![2015-08-23_16_05_11_-_news_edit_news_article_id_7_-_contao_open_source_cms_3_5](https://cloud.githubusercontent.com/assets/4976687/9428516/e3c747b8-49b0-11e5-8a54-256e23889f36.png)

**Comment by cyberlussi** [comment]
Habe es mal im reinen DCA in Contao nachgespielt ... gleicher Effekt bei reiner Zeitanzeige.
contao/core#7983

**Comment by discordier** [comment]
Dann mache ich das hier nun zu, muss im core behoben werden.
