### ISSUE TITLE
[TNG] Rendersetting Format G:i \U\h\r klappt nicht

### ISSUE THREAD

**Issue by cyberlussi** [MetaModels/attribute_timestamp#11]
Hi,

nach PHP date() sollte "G:i \U\h\r" ja "20:00 Uhr" ausgeben,  wenn ich das in das Formatfeld Einstellungen mache erscheint aber 

20:00 \1406491200\08\Sun, 27 Jul 2014 20:00:00 +0000

Das date escaping scheint da nicht durchzukommen ...

**Comment by xantippe** [comment]
als Bug würde ich das nicht sehen... das "Uhr" gehört m.E. eher ins Template...

wenn man das aber dennoch benötigt, kann man die Umwandlung des Slashes in HTML-Entitäten abstellen, so dass auch ```U\h\r``` in der Datenbank landet und nicht ```&#92;U&#92;h&#92;r```

per dcaconfig.php kann man das umstellen:

```php
$GLOBALS['TL_DCA']['tl_metamodel_rendersetting']['fields']['timeformat']['eval']['decodeEntities'] = true;
```
siehe Screenshot mit ```\J\a\h\r```
