### ISSUE TITLE
[Tng] Format timestamp attribute

### ISSUE THREAD

**Issue by PaoloB** [MetaModels/attribute_timestamp#12]
Hi,
i have update my MetaModels to TNG version.

I have a timestamp filed on my application.
If I insert a new record or update a record, I have this error:
DateTime::__construct(): Failed to parse time string (24/05/2014) at position 0 (2): Unexpected character

The date is 24/05/2014

In Contao the date format is d/m/Y
if the date is similar to 05/10/2013, the error is not present
I think it's a problem with the date format.

**Comment by discordier** [comment]
See contao/core#7721
