### ISSUE TITLE
Wrong grouping by date field

### ISSUE THREAD

**Issue by seaneble** [MetaModels/attribute_timestamp#16]
It appears as though grouping elements by a date field is not supported correctly. This is how the list is displayed:

![listenansicht](https://cloud.githubusercontent.com/assets/1255670/6896742/db0e21ee-d6ee-11e4-829a-62afd177d02a.png)

But actually, the date of the elements is set to 01.01.2010, not 01.01.1970:

![datum](https://cloud.githubusercontent.com/assets/1255670/6896740/d9bfb618-d6ee-11e4-9534-ff6232f20ac5.png)

And these are the settings:

![einstellungen](https://cloud.githubusercontent.com/assets/1255670/6896738/d73951e2-d6ee-11e4-8091-a0cc12895710.png)

**Comment by xantippe** [comment]
@seaneble kannst Du das mit einem aktuellen MM testen - bei der Sortierung/Guppierung hat(te) sich einiges getan...

**Comment by seaneble** [comment]
Looks good. Also some very interesting other changed in the meantime. I need to read the commits :smile:
