### ISSUE TITLE
Datepicker works wrong after date is once selected

### ISSUE THREAD

**Issue by daniel-nemeth** [MetaModels/attribute_timestamp#19]
Hi!
I'm using the timestamp attribute with 'Date and time' format and the datepicker.
But there is currently an issue with the datepicker afterwards a date/time have been selected.

First I select a date and time with the datepicker:
![datepicker1](https://cloud.githubusercontent.com/assets/5083254/15847723/6ae98426-2c88-11e6-9092-21d9a07aaa4b.png)

After a date and time have been inserted into the timestamp field I click on the datepicker again and now it displays 1970/01/01:
![datepicker2](https://cloud.githubusercontent.com/assets/5083254/15847733/83a53e9c-2c88-11e6-8373-14b7d01c9742.png)

I'm using Contao 3.5.12 with Composer:
![composer](https://cloud.githubusercontent.com/assets/5083254/15847750/b286da18-2c88-11e6-91ee-cbb77766cba8.png)

Thanks for your great work!

**Comment by zonky2** [comment]
I test with
C 3.5.12
MM a11
DCG hf/b36
Attr-TS 2.0.0-alpha3 Referenz: 3ad1df10

=> works fine

![shot224](https://cloud.githubusercontent.com/assets/1045318/15848021/822ce202-2c8a-11e6-905b-9dcff187deb8.jpg)

**Comment by daniel-nemeth** [comment]
The format string is taken from systems default. The correct format for a time in austria would be 18.25. But if this is the only problem I'll gonna change it to 18:25.

Thanks

**Comment by zonky2** [comment]
> The format string is taken from systems default

which format string has you defined at your contao system?

**Comment by daniel-nemeth** [comment]
Before: d.m.Y - H.i
Now: d.m.Y - H:i

**Comment by zonky2** [comment]
o.k. - I understand... I think, it´s a bug, but its at MM or Datepicker?

**Comment by daniel-nemeth** [comment]
Thats a good question. I currently have no idea which extension have a datim field, news and events seperates this two values.

**Comment by zonky2** [comment]
```d.m.Y H.i``` works fine

**Comment by daniel-nemeth** [comment]
d.m.Y - H.i with minus too?

**Comment by zonky2** [comment]
the "minus" it´s a "string character" - look at PHP date()
the correct format is ```d.m.Y \- H.i``` but you should update the input field at system settings
look at https://github.com/MetaModels/attribute_timestamp/issues/11#issuecomment-186925876

pls test it...

**Comment by zonky2** [comment]
you can use the tormat string without slash - minus is correct character at format string
test:
```php
$ts = 1465280880;
echo date('d.m.Y - H.i', $ts);
// 06.06.2016 - 23.28
```
its a problem of the picker
http://mootools.net/forge/p/mootools_datepicker
http://mootools.net/more/docs/1.6.0/Types/Date#Date:format
