### ISSUE TITLE
FEE - Property datetime (timestamp) does not accept the value date time

### ISSUE THREAD

**Issue by stu2019** [MetaModels/attribute_timestamp#35]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/attribute_timestamp/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |    7.4      |                                  |
| Contao version:                     |     4.9.13     |                                  |
| MetaModels version:                 |    2.2@dev      |                                  |
| Installation via composer           | (yes) |                                  |
| Installed MetaModels packages       |    all      |                                  |

## Issue description
FEE - Property datetime (timestamp) did not accept the value date time

## Steps to reproduce
Create an attribute date / Datum with the Schema Datum und Uhrzeit
Display the field in FEE in the Browser
Type a number or the date and time.

## Describe the behaviour of the application
We will see the error message
Das Feld "date-time" darf höchstens 10 Zeichen lang sein!
Property datetime (timestamp) did not accept the value (The values differ. Encountered type integer expected string (Found 0, expected '1970-01-01 00:00')).

## Describe the expected behaviour of the application
It should be possible to type the date and the time as 03.02.2020 12:12
If defined in the attributes it works for just the date 03.02.2020
and also for Jost the time 12:12

## Screenshots
<img width="1018" alt="Bildschirmfoto 2021-04-07 um 22 22 38" src="https://user-images.githubusercontent.com/49641522/113929546-7ec95100-97f0-11eb-83ba-335fd903d122.png">
<img width="1117" alt="Bildschirmfoto 2021-04-07 um 22 16 35" src="https://user-images.githubusercontent.com/49641522/113929576-84bf3200-97f0-11eb-967f-820e2b331408.png">

(Add some visual love or even a video if you can)

**Comment by zonky2** [comment]
Contao sets the maxlength of the form input to 10 based on the database field size - we have to override this.
The question is, to what size?

**Comment by zonky2** [comment]
fixed in MM 2.2

see also https://github.com/contao/contao/issues/2978

**Comment by stu2019** [comment]
Hallo

Ich bekomme seit neuestem die als Screenshot angehängte Fehlermeldung: 
Template metamodel_prerendered_listing_article not found (it is maybe within a unreachable theme folder?). 

Bisher habe ich meine Template im Verzeichnis Template/zero-one (dem Template-Ordner des 0.1 Themen von dir) abgelegt.
Und dies hat problemlos funktioniert.

Jetzt geht das wohl nicht mehr.
Ich muss das Template nach Template verschieben.

Ist das ein Fehler oder so gewollt?




Viele Grüße

Thomas Stuckenbrok
Erbshausener Straße 42a, 97262 Erbshausen, e-mail: ***@***.***

**Comment by zonky2** [comment]
Welche Fehlermeldungen? War kein Anhang dabei…

 

Von: stu2019 ***@***.***> 
Gesendet: Montag, 3. Mai 2021 10:51
An: MetaModels/attribute_timestamp ***@***.***>
Cc: zonky2 ***@***.***>; State change ***@***.***>
Betreff: Re: [MetaModels/attribute_timestamp] FEE - Property datetime (timestamp) does not accept the value date time (#35)

 

Hallo

Ich bekomme seit neuestem die als Screenshot angehängte Fehlermeldung: 
Template metamodel_prerendered_listing_article not found (it is maybe within a unreachable theme folder?). 

Bisher habe ich meine Template im Verzeichnis Template/zero-one (dem Template-Ordner des 0.1 Themen von dir) abgelegt.
Und dies hat problemlos funktioniert.

Jetzt geht das wohl nicht mehr.
Ich muss das Template nach Template verschieben.

Ist das ein Fehler oder so gewollt?




Viele Grüße

Thomas Stuckenbrok
Erbshausener Straße 42a, 97262 Erbshausen, e-mail: ***@***.*** <mailto:***@***.***>

**Comment by stu2019** [comment]
Vergessen: Die Meldung kommt bei der Anzeige im Backend, zum Render im FE scheint es im Theme Verzeichnis gefunden zu werden.

Viele Grüße

Thomas Stuckenbrok
Erbshausener Straße 42a, 97262 Erbshausen, e-mail: ***@***.***

**Comment by zonky2** [comment]
wenn Du ein Template für das BE anlegst, muss das direkt in das Verzeichnis /templates - das war schon immer so und liegt an Contao

Im BE gibt es keine Zuordnung zu (FE-) Themes - daher können auch keine Unterordner von Themes aufgelöst werden ... im FE ist das anders, da es hier eine Zuordnung zu dem Theme über das Layout gibt.

**Comment by stu2019** [comment]
OK, danke.

Ist mir so wohl noch nicht aufgefallen.

Viele Grüße

Thomas Stuckenbrok
Erbshausener Straße 42a, 97262 Erbshausen, e-mail: ***@***.***
