### ISSUE TITLE
Timestamp korrigiert Daten die vor 1901 liegen falsch

### ISSUE THREAD

**Issue by AgentCT** [MetaModels/attribute_timestamp#6]
Das Timestamp-Feld kennt ein Datum erst ab 1901, ich habe aber Daten die zum Beispiel im Jahr 1863 liegen.

Das Feld korrigiert diese dann immer fälschlicherweis auf 1901.

Contao 2.x verarbeitet das Datum korrekt, auch der Datepicker übergibt ein korrektes Datum ans Datumsfeld.

**Comment by discordier** [comment]
@stefanheimes Der upgradehandler fehlt noch?

**Comment by xantippe** [comment]
Thema Upgradehandler: siehe auch https://github.com/MetaModels/attribute_combinedvalues/issues/7#issuecomment-186022189

**Comment by discordier** [comment]
Upgradehandler has been added, please test.

**Comment by zonky2** [comment]
*Upgrade-Handler:*
ich verstehe den Upgrade-Handler nicht ganz - seit alpha3 ist das Feld doch schon auf bigint(10)...

*Datum < 1970:*
setzt man das Feld wie bei tl_member das dateOfBirth auf den Typ varchar(11) wird auch ein Datum kleiner 1970 gespeichert

![shot215](https://cloud.githubusercontent.com/assets/1045318/15674578/d4700ed8-273d-11e6-914f-5437506bf66a.jpg)

**Comment by zonky2** [comment]
*Upgrade-Handler*
* mit attribute_tiumestamp alpha3 Attribut angelegt und in DB von bigint(10) auf int(10) gesetzt
![shot216](https://cloud.githubusercontent.com/assets/1045318/15699859/a573e24c-27d0-11e6-9192-de171dab4182.jpg)

* Update ```Installing metamodels/attribute_timestamp (dev-hotfix/2.0.0-alpha4 7bcf92a)``` => DB-Feld ist auf bigint(10) geändert
![shot217](https://cloud.githubusercontent.com/assets/1045318/15699865/ae50db72-27d0-11e6-9c53-2f771856e19a.jpg)

*Datum < 13.12.1901*
bis zum 14.12.1901 sind Eingaben unkritisch - bei einem kleineren Datum kommt es auf die PHP-Version an. d.h. ob 32bit oder 64bit

bei 32bit ist beim 13.12.1901 Schluss
![shot219](https://cloud.githubusercontent.com/assets/1045318/15701066/3505d940-27d8-11e6-8cc7-b1b9ea675fcf.jpg)

Eine Lösung des Problems ist neben dem Wechsel auf ein 64bit-System der Wechsel von der PHP-Version ```strtotime``` zum Consructor ```DateTime```, da dieser immer mit 64bit arbeitet

**Comment by zonky2** [comment]
ich habe die Sache nochmal geprüft: auf einem 64bit-System können Datums-Angaben vor 1901 und nach 2038 eingegeben werden - und das schon seit alpha3 (alpha4 auch geprüft)

![shot221](https://cloud.githubusercontent.com/assets/1045318/15726852/51e49c6a-2853-11e6-942a-16e3a1775a13.jpg)
