### ISSUE TITLE
Ausgabe des Datums im Filter erfolgt als Timestamp.

### ISSUE THREAD

**Issue by planepix** [MetaModels/attribute_timestamp#9]
Hallo zusammen,

aktuell ist Metamodel 1.1 nighly in Contao 3.2.10 eingerichtet.

Das Feld "Datum" wird in einer Detailansicht auch als "lesbares Datum (23.06.2014)" ausgegeben.
![mm-date-fe-detail](https://cloud.githubusercontent.com/assets/1823889/3278771/7d90ce54-f3d2-11e3-89d8-4ff7918e1b82.png)

Als Filter ausgewählt wird nur der Timestamp angezeigt.

![mm-date-filter](https://cloud.githubusercontent.com/assets/1823889/3278764/fa5b01da-f3d1-11e3-8300-1d00b7bb8da1.png)

Ist das noch ein Bug oder müssen Templates angepasst werden, um eine lesbare Datumsausgabe zu erreichen?

Besten Dank und Gruß
Thomas

**Comment by xantippe** [comment]
@planepix welchen Filter meinst Du BE oder FE?

**Comment by planepix** [comment]
@xantippe: FE

**Comment by xantippe** [comment]
was für eine Filterregel hast Du angelegt?

**Comment by planepix** [comment]
Projekt / Installation existiert nicht mehr :(

**Comment by xantippe** [comment]
ich glaube, dann kann das Ticket geschlossen werden, da bei Filterregel "Auswahl" ein [timestamp] nicht (mehr?) zur Auswahl steht

**Comment by planepix** [comment]
Ich kann mir einen solchen Filtern nochmal neu bauen und testen ob das mittlerweile geht. Sonst gerne schliessen.

**Comment by xantippe** [comment]
na, dann teste doch bitte nochmal, damit wir auf "Nummer sicher" gehen..

**Comment by planepix** [comment]
Eben getestet: Contao 3.5.6 und NightlyBuild von gestern. Filter mit lesbarem Datum nun im FE.

**Comment by xantippe** [comment]
Dank!
